const now = Date.now();
const recent = (minutesAgo) => new Date(now - minutesAgo * 60 * 1000).toISOString();

export function createSeedState() {
  return {
    users: [
      {
        id: "u-demo",
        name: "Ari",
        avatar: "⚡",
        teamId: "team-green",
        xp: 860,
        level: 7,
        streak: 4,
        weeklyMissions: 4,
        joinedAt: recent(240)
      }
    ],
    teams: [
      {
        id: "team-green",
        code: "GREEN7",
        name: "Green Circuit",
        shortName: "Circuit",
        color: "#58CC02",
        darkColor: "#3D9200",
        emblem: "⚡",
        score: 2840,
        kwhSaved: 18.6,
        wasteMinutesStopped: 1140,
        rewardCredits: 12.4,
        memberCount: 8,
        streak: 6
      },
      {
        id: "team-gold",
        code: "SOLAR9",
        name: "Solar Sprinters",
        shortName: "Solar",
        color: "#FFC800",
        darkColor: "#C69600",
        emblem: "☀",
        score: 3110,
        kwhSaved: 20.8,
        wasteMinutesStopped: 1275,
        rewardCredits: 14.15,
        memberCount: 10,
        streak: 8
      },
      {
        id: "team-blue",
        code: "WATTS4",
        name: "Watt Watchers",
        shortName: "Watts",
        color: "#1CB0F6",
        darkColor: "#087DB4",
        emblem: "◉",
        score: 2475,
        kwhSaved: 16.1,
        wasteMinutesStopped: 987,
        rewardCredits: 10.8,
        memberCount: 7,
        streak: 5
      },
      {
        id: "team-purple",
        code: "NOVA3",
        name: "Nova Grid",
        shortName: "Nova",
        color: "#CE82FF",
        darkColor: "#8E45B8",
        emblem: "✦",
        score: 1980,
        kwhSaved: 12.7,
        wasteMinutesStopped: 779,
        rewardCredits: 8.3,
        memberCount: 6,
        streak: 3
      }
    ],
    missions: [
      {
        id: "mission-com3-projector",
        code: "COM3-AV",
        qrToken: "qr_com3_projector_2026",
        territoryId: "territory-central",
        title: "Projector power-down",
        shortTitle: "Projector",
        location: "COM3 • Seminar Room 2",
        type: "screen",
        icon: "▰",
        map: { longitude: 103.7745818, latitude: 1.2945826 },
        instruction: "Power off the labelled projector after the room is empty.",
        safety: "Only use the wall controller marked with the Jouling QR code.",
        expectedVisualEvidence: "A projector or controller visibly showing an off, standby, or black-screen state in an empty room.",
        powerBeforeKw: 0.42,
        powerAfterKw: 0.03,
        avoidedMinutes: 90,
        estimatedKwh: 0.585,
        xp: 60,
        credit: 0.45,
        difficulty: "Quick win",
        active: true,
        availableWindow: "After class",
        teamCompletions: {
          "team-green": { completedAt: recent(10), kwhSaved: 0.585, confidence: 0.94 }
        }
      },
      {
        id: "mission-study-lights",
        code: "LIB-LUX",
        qrToken: "qr_study_lights_2026",
        territoryId: "territory-central",
        title: "Lights out, level 2",
        shortTitle: "Lights",
        location: "Central Library • Study Zone",
        type: "lighting",
        icon: "✦",
        map: { longitude: 103.77302, latitude: 1.29664 },
        instruction: "Switch off the labelled row of lights once the zone is empty.",
        safety: "The QR is attached only to the approved lighting switch.",
        expectedVisualEvidence: "The labelled study-zone lights are visibly off and no one is using the zone.",
        powerBeforeKw: 0.76,
        powerAfterKw: 0,
        avoidedMinutes: 75,
        estimatedKwh: 0.95,
        xp: 80,
        credit: 0.7,
        difficulty: "Team task",
        active: true,
        availableWindow: "Quiet hours",
        teamCompletions: {
          "team-green": { completedAt: recent(7), kwhSaved: 0.95, confidence: 0.92 }
        }
      },
      {
        id: "mission-library-ac",
        code: "CLB-25C",
        qrToken: "qr_library_ac_2026",
        territoryId: "territory-central",
        title: "Close the cooling loop",
        shortTitle: "Cooling",
        location: "Central Library • Project Room",
        type: "cooling",
        icon: "❄",
        map: { longitude: 103.77331, latitude: 1.29649 },
        instruction: "When the room is empty, switch off the labelled air-conditioning controller and close the door.",
        safety: "Mission is active only outside booked hours. Do not touch the electrical panel.",
        expectedVisualEvidence: "The approved air-conditioning controller visibly reads off and the project-room door is closed.",
        powerBeforeKw: 1.2,
        powerAfterKw: 0.06,
        avoidedMinutes: 45,
        estimatedKwh: 0.855,
        xp: 120,
        credit: 1.25,
        difficulty: "Territory capture",
        active: true,
        availableWindow: "Now • no booking",
        featured: true,
        teamCompletions: {}
      },
      {
        id: "mission-utown-screen",
        code: "UTN-SCR",
        qrToken: "qr_utown_screen_2026",
        territoryId: "territory-utown",
        title: "Sleep the display wall",
        shortTitle: "Displays",
        location: "UTown • Collaboration Hub",
        type: "screen",
        icon: "▣",
        map: { longitude: 103.7738276, latitude: 1.3059749 },
        instruction: "Put the approved display wall into sleep mode after the event.",
        safety: "Use only the controller beside this QR code.",
        expectedVisualEvidence: "The display wall is dark or visibly in sleep mode, with the event area empty.",
        powerBeforeKw: 0.68,
        powerAfterKw: 0.04,
        avoidedMinutes: 120,
        estimatedKwh: 1.28,
        xp: 135,
        credit: 1.4,
        difficulty: "High impact",
        active: true,
        availableWindow: "After 6:00 PM",
        teamCompletions: {
          "team-gold": { completedAt: recent(18), kwhSaved: 1.28, confidence: 0.96 }
        }
      },
      {
        id: "mission-hall-sockets",
        code: "HALL-PLG",
        qrToken: "qr_hall_sockets_2026",
        territoryId: "territory-utown",
        title: "Stop standby drain",
        shortTitle: "Sockets",
        location: "Hall 4 • Common Lounge",
        type: "standby",
        icon: "⌁",
        map: { longitude: 103.7796945, latitude: 1.2911919 },
        instruction: "Switch off the labelled socket bank after the common lounge closes.",
        safety: "Only the green-labelled entertainment socket bank is included.",
        expectedVisualEvidence: "The green-labelled socket bank switch is visibly off and attached devices are not in active use.",
        powerBeforeKw: 0.18,
        powerAfterKw: 0.01,
        avoidedMinutes: 360,
        estimatedKwh: 1.02,
        xp: 105,
        credit: 0.95,
        difficulty: "Evening mission",
        active: true,
        availableWindow: "After 11:00 PM",
        teamCompletions: {
          "team-gold": { completedAt: recent(15), kwhSaved: 1.02, confidence: 0.9 }
        }
      },
      {
        id: "mission-innovation-door",
        code: "INN-DOOR",
        qrToken: "qr_innovation_door_2026",
        territoryId: "territory-utown",
        title: "Seal the cool air",
        shortTitle: "Door",
        location: "Innovation 4.0 • Studio",
        type: "cooling",
        icon: "↥",
        map: { longitude: 103.7756884, latitude: 1.2945805 },
        instruction: "Close the approved studio door while air-conditioning is running.",
        safety: "Do not lock the door or obstruct access routes.",
        expectedVisualEvidence: "The named studio door is fully closed while the room remains safely accessible.",
        powerBeforeKw: 1.48,
        powerAfterKw: 1.2,
        avoidedMinutes: 90,
        estimatedKwh: 0.42,
        xp: 70,
        credit: 0.35,
        difficulty: "Quick win",
        active: false,
        availableWindow: "Class in progress",
        teamCompletions: {}
      },
      {
        id: "mission-e2-lights",
        code: "E2-LUX",
        qrToken: "qr_e2_lights_2026",
        territoryId: null,
        title: "Lights out at E2",
        shortTitle: "E2 Lights",
        location: "Engineering 2 • Tutorial Room",
        type: "lighting",
        icon: "☼",
        map: { longitude: 103.7711, latitude: 1.30025 },
        instruction: "When the tutorial room is empty, switch off the approved row of ceiling lights.",
        safety: "Use only the wall switch carrying the Jouling label. Keep corridor and emergency lighting on.",
        expectedVisualEvidence: "The labelled tutorial-room lights are visibly off and the room is empty.",
        powerBeforeKw: 0.48,
        powerAfterKw: 0,
        avoidedMinutes: 45,
        estimatedKwh: 0.36,
        xp: 45,
        credit: 0.3,
        difficulty: "Easy win",
        active: true,
        availableWindow: "Available now",
        teamCompletions: {}
      },
      {
        id: "mission-md6-screen",
        code: "MD6-SCR",
        qrToken: "qr_md6_screen_2026",
        territoryId: null,
        title: "Sleep the lobby screen",
        shortTitle: "Lobby Screen",
        location: "MD6 • Student Lobby",
        type: "screen",
        icon: "▣",
        map: { longitude: 103.7812, latitude: 1.2955 },
        instruction: "Put the approved information display into sleep mode after the lobby event ends.",
        safety: "Use only the labelled display controller and do not disconnect cables.",
        expectedVisualEvidence: "The named lobby display is dark or visibly in sleep mode and no event is active.",
        powerBeforeKw: 0.32,
        powerAfterKw: 0.03,
        avoidedMinutes: 90,
        estimatedKwh: 0.435,
        xp: 55,
        credit: 0.4,
        difficulty: "Quick win",
        active: true,
        availableWindow: "After events",
        teamCompletions: {}
      },
      {
        id: "mission-sde4-ac",
        code: "SDE4-AC",
        qrToken: "qr_sde4_ac_2026",
        territoryId: null,
        title: "End empty-room cooling",
        shortTitle: "Studio AC",
        location: "SDE4 • Project Studio",
        type: "cooling",
        icon: "❄",
        map: { longitude: 103.7703, latitude: 1.296 },
        instruction: "After the studio empties, switch off the approved air-conditioning controller and close the door.",
        safety: "Do not touch electrical panels or controls without a Jouling label.",
        expectedVisualEvidence: "The labelled controller visibly reads off, the studio is empty, and the door is closed.",
        powerBeforeKw: 1.05,
        powerAfterKw: 0.05,
        avoidedMinutes: 40,
        estimatedKwh: 0.667,
        xp: 75,
        credit: 0.65,
        difficulty: "Easy team win",
        active: true,
        availableWindow: "Available now",
        teamCompletions: {}
      }
    ],
    zoneMissions: [
      {
        id: "zone-kent-ridge-sweep",
        kind: "team-sweep",
        title: "Kent Ridge Power Sweep",
        location: "Kent Ridge South Cluster",
        icon: "⚡",
        center: { longitude: 103.7646, latitude: 1.2922 },
        radiusMeters: 310,
        xpMultiplier: 1.5,
        assignedTeamId: "team-green",
        color: "#7B61FF",
        darkColor: "#5139C5",
        status: "LIVE",
        description: "Your team owns this temporary sweep zone. Check any approved room inside it and stop unnecessary electricity use.",
        instructions: [
          "Check unoccupied rooms for approved lights left on.",
          "Switch off labelled AC, projectors, or screens that are running unnecessarily.",
          "Every verified action inside the circle earns 1.5× XP during the sweep."
        ],
        safety: "Only use controls with Jouling labels. Skip occupied rooms and never touch electrical panels."
      }
    ],
    territories: [
      {
        id: "territory-central",
        name: "Central Commons",
        areaSqFt: 18500,
        nodeIds: ["mission-com3-projector", "mission-study-lights", "mission-library-ac"],
        polygon: [[103.7745818, 1.2945826], [103.77302, 1.29664], [103.77331, 1.29649]],
        ownerTeamId: "team-gold",
        previousOwnerTeamId: "team-blue",
        strength: 61,
        capturedAt: recent(95),
        teamProgress: {
          "team-green": {
            completedNodeIds: ["mission-com3-projector", "mission-study-lights"],
            completed: 2,
            required: 3,
            percent: 67,
            verifiedKwh: 1.535
          }
        }
      },
      {
        id: "territory-utown",
        name: "UTown Triangle",
        areaSqFt: 22400,
        nodeIds: ["mission-utown-screen", "mission-hall-sockets", "mission-innovation-door"],
        polygon: [[103.7738276, 1.3059749], [103.7796945, 1.2911919], [103.7756884, 1.2945805]],
        ownerTeamId: "team-gold",
        previousOwnerTeamId: "team-purple",
        strength: 78,
        capturedAt: recent(64),
        teamProgress: {}
      }
    ],
    dailyMatchups: [
      {
        id: "daily-green-blue",
        teamAId: "team-green",
        teamBId: "team-blue",
        teamAScore: 460,
        teamBScore: 405,
        startsAt: new Date(new Date(now).setHours(0, 0, 0, 0)).toISOString(),
        endsAt: new Date(new Date(now).setHours(24, 0, 0, 0)).toISOString(),
        rewardXp: 180
      },
      {
        id: "daily-gold-purple",
        teamAId: "team-gold",
        teamBId: "team-purple",
        teamAScore: 510,
        teamBScore: 438,
        startsAt: new Date(new Date(now).setHours(0, 0, 0, 0)).toISOString(),
        endsAt: new Date(new Date(now).setHours(24, 0, 0, 0)).toISOString(),
        rewardXp: 180
      }
    ],
    attempts: [],
    activity: [
      { id: "a1", teamId: "team-gold", text: "Solar Sprinters defended UTown Triangle", at: recent(9) },
      { id: "a2", teamId: "team-green", text: "Green Circuit stabilised Library Lights", at: recent(7) },
      { id: "a3", teamId: "team-blue", text: "Watt Watchers saved 0.8 kWh at Engineering", at: recent(14) }
    ]
  };
}
